### ISSUE TITLE
Integration broken with 2023.5.0b1

### ISSUE THREAD

**Issue by julianrinaldi** [dreed47/redfin#9]
I'm getting this error:

```
Logger: homeassistant.config_entries
Source: config_entries.py:367
First occurred: 5:11:51 PM (1 occurrences)
Last logged: 5:11:51 PM

Error importing platform config_flow from integration redfin to set up redfin configuration entry: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/Users/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity_registry.py)
```

Worked fine with 2023.5.0b0

**Comment by Madj42** [comment]
Same here.

**Comment by Madj42** [comment]
#10 This is fixed in this PR.

**Comment by gawelko** [comment]
I updated from Home Assistant Core 2023.4.6 to 2023.5 and received the following error:

Logger: homeassistant.config_entries
Source: config_entries.py:367
First occurred: 6:32:00 AM (1 occurrences)
Last logged: 6:32:00 AM

Error importing platform config_flow from integration redfin to set up redfin configuration entry: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)

**Comment by dreed47** [comment]
resolved in new release
